manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: englmaxi
      url-base: https://github.com/englmaxi
  projects:
    - name: zmk
      remote: petejohanson
      revision: core/move-to-zephyr-4-1
      import: app/west.yml
    - name: zmk-config
      remote: englmaxi
      revision: master
  self:
    path: config
